ALTER TABLE `users` ADD `Address` TEXT NULL AFTER `CellphoneNumber`;
ALTER TABLE `config` ADD `Value2` VARCHAR(500) NULL DEFAULT NULL AFTER `StatusId`, ADD `Value3` VARCHAR(500) NULL DEFAULT NULL AFTER `Value2`, ADD `Value4` VARCHAR(500) NULL DEFAULT NULL AFTER `Value3`, ADD `Value5` VARCHAR(500) NULL DEFAULT NULL AFTER `Value4`;

ALTER TABLE `config` ADD `Label2` TEXT NULL DEFAULT NULL AFTER `Label`, ADD `Label3` TEXT NULL DEFAULT NULL AFTER `Label2`, ADD `Label4` TEXT NULL DEFAULT NULL AFTER `Label3`, ADD `Label5` TEXT NULL DEFAULT NULL AFTER `Label4`;